name: CI
on: push
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        # As of 2021-05-25, Python 3.9 does not have TensorFlow Quantum available.
        # Also, Python 3.9 does not have TensorFlow 2.4.1 available, as 2.5.0 is its oldest supported version.
        python-version: 3.8
    - name: Print Python version
      run: python -V
    - name: Checkout
      uses: actions/checkout@v2
    - name: Load pip cache
      uses: actions/cache@v2
      with:
        path: .pip
        key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          pip-${{ runner.os }}-
          pip-
    - name: Install requirements
      # TensorFlow has to be installed separately before or after TensorFlow Quantum due to dependency conflicts.
      # See the requirements.txt for details.
      run: |
        pip --cache-dir=.pip install --upgrade pip
        pip --cache-dir=.pip install pylint wheel
        pip --cache-dir=.pip install tensorflow==2.4.1
        pip --cache-dir=.pip install tensorflow-quantum==0.5.0
        pip --cache-dir=.pip install -r requirements.txt
    - name: Test libraries
      run: python ${{ github.workspace }}/test_libs.py
    - name: Install FOSSA
      run: |
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
        - name: Run FOSSA
          run: fossa analyze
          env:
            FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
    - name: Convert notebooks
      run: jupyter nbconvert --to=script --output-dir=${{ github.workspace }}/converted_notebooks/ ${{ github.workspace }}/*.ipynb
    - name: Run Pylint
      run: pylint converted_notebooks 2>&1 | tee pylint.txt
      working-directory: ${{ github.workspace }}
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: Lint
        path: |
          ${{ github.workspace }}/pylint.txt
        if-no-files-found: error
